### ISSUE TITLE
Not keeping running after 0th epoch ends.

### ISSUE THREAD

**Issue by gogyzzz** [taylorlu/ghostvlad-speaker#2]
![image](https://user-images.githubusercontent.com/8141431/58315589-c63cd300-7e4c-11e9-9577-587d0e87859e.png)

num of workers: 24

After iteration of 426x, all processes in iterator() function seems to be stopped.
![image](https://user-images.githubusercontent.com/8141431/58315872-4feca080-7e4d-11e9-928d-1a7306f203dd.png)

But the next epoch won't start.

**Comment by taylorlu** [comment]
Sorry, there seems has a bug in `audio_producer.py` when finish an epoch.
you can renew an instance when finished an epoch in `train.py`
```
    producer = audio_producer.AudioProducer(argv['json_path'], argv['batch_size'],
                                            sample_rate=argv['sample_rate'],
                                            min_duration=argv['min_duration'],
                                            max_duration=argv['max_duration'])
```

**Comment by gogyzzz** [comment]
Did you mean putting the code after run_epoch() ?

I found the function works well when I cut the length of number of batches.
![image](https://user-images.githubusercontent.com/8141431/58318689-42d2b000-7e53-11e9-9090-6844545c7ee4.png)

**Comment by gogyzzz** [comment]
I used the trick like below, and it works. 
![image](https://user-images.githubusercontent.com/8141431/58323025-b11c7000-7e5d-11e9-8575-426b26a0f5f7.png)
